services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vox-echo
    volumes:
      - vox-echo-data:/var/lib/postgresql/data
    networks:
      - vox-echo-network
    ports:
      - "5432:5432"

networks:
  vox-echo-network:
    driver: bridge

volumes:
  vox-echo-data:
